### ISSUE TITLE
Doesn't work with flexible height parent?

### ISSUE THREAD

**Issue by mbrookes** [vaiRk/responsive-fixed-data-table#4]
I seem to have to apply a fixed height to the parent div - at which point I might as well apply a fixed height to <Table>, defeating the purpose of responsive-fixed-data-table...

What am I missing?

**Comment by vaiRk** [comment]
The table should take 100% of the space available in the parent container. I built it for a very specific use case I had while working on a project and haven't done a lot of testing on it.

Sorry to hear is not working as you think it should, I'd be glad to take a look at your case if you provide some example :)

**Comment by mbrookes** [comment]
Thanks. 

Here's the HTML:

``` html
<div className="main-layout-wrapper">
  <div className="main-layout-header">
    Header goes here...
  </div>

  <div className="main-layout-content">
    Table goes here...
  </div>

  <div className="main-layout-footer">
    Footer goes here
  </div>
</div>
```

and CSS:

``` css
html, body {
    margin:0;
    height:100vh;
}

.main-layout-wrapper {
    display: -webkit-flex;
    display: flex;

    -webkit-flex-direction: column;
    flex-direction: column;

    height: 100vh; /* wrapper fills viewport height - doesn't work for Mobile Safari with overlaid toolbars. */
}

.main-layout-header {
    height: 64px;
    min-height: 64px; /* Seems to be needed for WebView in addition to / instead of height */
    overflow-y: hidden;
}

.main-layout-content {
    -webkit-flex-grow: 1;
    flex-grow: 1;
    overflow-y: hidden;
}

.main-layout-footer {
    height: 48px;
    min-height: 48px; /* Seems to be needed for WebView in addition to / instead of height */
    overflow-y: hidden;
}
```
